# Generated by Django 4.1.7 on 2023-03-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarpanel',
            name='canton',
            field=models.CharField(blank=True, choices=[('USK', 'Unsko-sanski kanton'), ('PK', 'Posavski kanton'), ('TK', 'Tuzlanski kanton'), ('ZDK', 'Zeničko-dobojski kanton'), ('BPK', 'Bosansko-podrinjski kanton Goražde'), ('SBK', 'Srednjobosanski kanton'), ('HNK', 'Hercegovačko-neretvanski kanton'), ('ZHK', 'Zapadnohercegovački kanton'), ('KS', 'Kanton Sarajevo'), ('K10', 'Kanton 10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='canton',
            field=models.CharField(blank=True, choices=[('USK', 'Unsko-sanski kanton'), ('PK', 'Posavski kanton'), ('TK', 'Tuzlanski kanton'), ('ZDK', 'Zeničko-dobojski kanton'), ('BPK', 'Bosansko-podrinjski kanton Goražde'), ('SBK', 'Srednjobosanski kanton'), ('HNK', 'Hercegovačko-neretvanski kanton'), ('ZHK', 'Zapadnohercegovački kanton'), ('KS', 'Kanton Sarajevo'), ('K10', 'Kanton 10')], max_length=3, null=True),
        ),
    ]
