# Generated by Django 4.1.7 on 2023-04-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_solarpanel_canton_alter_solarpanel_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarpanel',
            name='canton',
            field=models.CharField(blank=True, choices=[('USK', 'Una-Sana canton'), ('PK', 'Posavina canton'), ('TK', 'Tuzla canton'), ('ZDK', 'Zenica-Doboj canton'), ('BPK', 'Bosnian-Podrinje canton of Goražde'), ('SBK', 'Central Bosnian Canton'), ('HNK', 'Herzegovina-Neretva Canton'), ('ZHK', 'West Herzegovina Canton'), ('KS', 'Sarajevo Canton'), ('K10', 'Canton 10')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='entity',
            field=models.CharField(choices=[('RS', 'Republic of Srpska'), ('FBiH', 'Federation of Bosnia and Herzegovina'), ('BD', 'District Brcko')], max_length=4),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='zone',
            field=models.CharField(blank=True, choices=[('U', 'Urban'), ('R', 'Rural')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='canton',
            field=models.CharField(blank=True, choices=[('USK', 'Una-Sana canton'), ('PK', 'Posavina canton'), ('TK', 'Tuzla canton'), ('ZDK', 'Zenica-Doboj canton'), ('BPK', 'Bosnian-Podrinje canton of Goražde'), ('SBK', 'Central Bosnian Canton'), ('HNK', 'Herzegovina-Neretva Canton'), ('ZHK', 'West Herzegovina Canton'), ('KS', 'Sarajevo Canton'), ('K10', 'Canton 10')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='entity',
            field=models.CharField(choices=[('RS', 'Republic of Srpska'), ('FBiH', 'Federation of Bosnia and Herzegovina'), ('BD', 'District Brcko')], max_length=4),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='zone',
            field=models.CharField(blank=True, choices=[('U', 'Urban'), ('R', 'Rural')], max_length=1, null=True),
        ),
    ]
