# Generated by Django 4.1.7 on 2023-04-12 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_solarpanel_canton_alter_solarpanel_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarpanel',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
