# Generated by Django 4.1.7 on 2023-04-12 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_solarpanel_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarpanel',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
